# Generated by Django 5.2.6 on 2025-09-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.CharField(max_length=6)),
                ('name', models.TextField()),
                ('fundType', models.IntegerField()),
                ('netAsset', models.BigIntegerField(null=True)),
            ],
        ),
    ]
