# Generated by Django 5.2.6 on 2025-09-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='regNo',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
